### ISSUE TITLE
Vamos con el GHC!!

### ISSUE THREAD

**Issue by asanzo** [pdepjm/2023-tp0-presentacion-ignariolffi#1]
- Ñoquis de calabaza rellenos de muzzarella, mi comida de ayer, espero que, siendo de la pasta, hayas también aprovechado 😃 
- Grande por instalar Haskell. ¿En qué SO? ¿Windows?
- Novela para recomendar, "Dioses menores" de Terry Pratchett. Es parte de la saga de Mundodisco, es una fantasía humorística, me encanta, estot enganchadísimo con Mundodisco.

**Comment by ignariolffi** [comment]
- Los ñoquis, para mi la mejor pasta por lejos, voy a probarlos rellenos!
- Lo instale en Windows, unas pequeñas complicaciones con agregar al PATH git pero se pudo 😄😄
- La voy a buscar! Yo por mi parte fanatico de la saga de Cancion de Hielo y Fuego de George RR Martin. Un universo muy amplio, lleno de personajes y una historia que le dan vida a la serie Game Of Thrones
- Crees que le haga falta algo a mi repo? Estoy abierto a recomendaciones!

**Comment by asanzo** [comment]
Ta perfecto!!!

Yo tengo encolado Canción de Hielo y Fuego, leí la mitad de Juego de Tronos y lo pausé. Me gustaría que don Jorge la termine y deje de dar vueltas así la leo sin miedo a que quede inconclusa.

El repo ta perfecto 💯

**Comment by ignariolffi** [comment]
Sii estoy con el mismo miedo de que la deje y quede sin terminar, gracias por los comments!
